Repository TRIP-SPOT/SPOT-Client, pull requests merged in 2024-08, with the labels that each got.

#16 feat: 상세보기 페이지 추가
  .yarn/install-state.gz
  packages/design-system/src/Font.tsx
  packages/react-native/.eslintrc.js
  packages/react-native/package.json
  packages/react-native/src/assets/HeartIcon.tsx
  packages/react-native/src/components/CardSlider.tsx
  packages/react-native/src/components/common/Card.tsx
  packages/react-native/src/components/common/SearchBar.tsx
  packages/react-native/src/components/common/Tag.tsx
  packages/react-native/src/components/common/WordBreak.tsx
  packages/react-native/src/constants/HEADER_STYLE.ts
  packages/react-native/src/layouts/BackGroundGradient.tsx
  packages/react-native/src/pages/Detail.tsx
  packages/react-native/src/pages/Home.tsx
  packages/react-native/src/pages/MyPage.tsx
  packages/react-native/src/routes/BottomTabNavigator.tsx
  packages/react-native/src/routes/HomeStackNavigator.tsx
  packages/react-native/src/routes/MyPageStackNavigator.tsx
  packages/react-native/src/types/navigation.ts
  packages/react-native/src/types/spot.ts
  yarn.lock
Labels: feat

#15 feat: maps 로그 페이지 UI구성
  packages/react-native/package.json
  packages/react-native/src/assets/DotMenuIcon.tsx
  packages/react-native/src/assets/PlusButtonIcon.tsx
  packages/react-native/src/assets/SortIcon.tsx
  packages/react-native/src/assets/mapData.ts
  packages/react-native/src/components/common/Header.tsx
  packages/react-native/src/components/maps/FloatingPlusButton.tsx
  packages/react-native/src/components/maps/LogCard.tsx
  packages/react-native/src/components/maps/LogCardList.tsx
  packages/react-native/src/components/signup/common/Header.tsx
  packages/react-native/src/layouts/BackGroundGradient.tsx
  packages/react-native/src/pages/Detail.tsx
  packages/react-native/src/pages/Maps/Log.tsx
  packages/react-native/src/pages/Maps/Maps.tsx
  packages/react-native/src/pages/Maps/ModifyLog.tsx
  packages/react-native/src/pages/Maps/PostLog.tsx
  packages/react-native/src/pages/Signup/Nickname.tsx
  packages/react-native/src/pages/Signup/NicknameProfile.tsx
  packages/react-native/src/pages/Signup/Profile.tsx
  packages/react-native/src/routes/BottomTabNavigator.tsx
  packages/react-native/src/routes/MapsStackNavigator.tsx
  packages/react-native/src/routes/SignupStackNavigator.tsx
  packages/react-native/src/stores/header.ts
  packages/react-native/src/types/map.ts
  packages/react-native/src/types/navigation.ts
  yarn.lock
Labels: feat

#17 feat: 닉네임 Storage저장 로직 추가
  packages/react-native/ios/Podfile.lock
  packages/react-native/ios/SPOTClient/PrivacyInfo.xcprivacy
  packages/react-native/package.json
  packages/react-native/src/apis/queries/useNicknameQuery.ts
  packages/react-native/src/pages/Home.tsx
  packages/react-native/src/pages/Login/Login.tsx
  packages/react-native/src/pages/MyPage.tsx
  packages/react-native/src/pages/Signup/Profile.tsx
  packages/react-native/src/utils/storage.ts
  yarn.lock
Labels: feat

#18 refactor: log -> record 네이밍 변경
  packages/react-native/src/components/common/Header.tsx
  packages/react-native/src/components/maps/LogCard.tsx
  packages/react-native/src/components/maps/RecordCard.tsx
  packages/react-native/src/components/maps/RecordCardList.tsx
  packages/react-native/src/components/signup/common/Header.tsx
  packages/react-native/src/pages/Maps/Maps.tsx
  packages/react-native/src/pages/Maps/ModifyRecord.tsx
  packages/react-native/src/pages/Maps/PostRecord.tsx
  packages/react-native/src/pages/Maps/Records.tsx
  packages/react-native/src/routes/MapsStackNavigator.tsx
Labels: refactor

#19 feat: record detail 페이지 구성
  packages/react-native/src/apis/queries/records/useRecordDetailQuery.ts
  packages/react-native/src/components/maps/RecordCardList.tsx
  packages/react-native/src/components/signup/common/Header.tsx
  packages/react-native/src/pages/Maps/RecordDetail.tsx
  packages/react-native/src/pages/Signup/Nickname.tsx
Labels: feat

#20 refactor: 논의 사항 합의
  packages/react-native/src/components/common/Header.tsx
  packages/react-native/src/components/maps/RecordCard.tsx
  packages/react-native/src/components/signup/common/Header.tsx
  packages/react-native/src/layouts/BackGroundGradient.tsx
  packages/react-native/src/pages/Detail.tsx
  packages/react-native/src/pages/Home.tsx
  packages/react-native/src/pages/Login/Login.tsx
  packages/react-native/src/pages/Maps/Maps.tsx
  packages/react-native/src/pages/Maps/RecordDetail.tsx
  packages/react-native/src/pages/Maps/Records.tsx
  packages/react-native/src/pages/MyPage.tsx
  packages/react-native/src/pages/MyPage/EditProfile.tsx
  packages/react-native/src/pages/MyPage/EditProfileWithNickname.tsx
  packages/react-native/src/pages/Signup/Nickname.tsx
  packages/react-native/src/pages/Signup/NicknameProfile.tsx
  packages/react-native/src/pages/Signup/Profile.tsx
  packages/react-native/src/routes/HomeStackNavigator.tsx
  packages/react-native/src/routes/MapsStackNavigator.tsx
  packages/react-native/src/routes/MyPageStackNavigator.tsx
  packages/react-native/src/routes/SignupStackNavigator.tsx
  packages/react-native/src/routes/StackNavigator.tsx
  packages/react-native/src/stores/header.ts
  packages/react-native/src/types/navigation.ts
Labels: refactor

#21 feat: record detail 선택 option bottom sheet 추가
  packages/react-native/src/components/maps/RecordCard.tsx
  packages/react-native/src/components/maps/RecordCardList.tsx
  packages/react-native/src/hooks/useBottomSheet.tsx
  packages/react-native/src/pages/Maps/Maps.tsx
  packages/react-native/src/pages/Maps/Records.tsx
Labels: feat, refactor
