Repository TRIP-SPOT/SPOT-Client, pull requests merged in 2024-09, with the labels that each got.

#23 feat: record post form 추가
  packages/design-system/src/TextField.tsx
  packages/react-native/ios/Podfile.lock
  packages/react-native/package.json
  packages/react-native/src/apis/mutations/usePostRecordMutation.ts
  packages/react-native/src/assets/Calendar.tsx
  packages/react-native/src/assets/PlusIcon.tsx
  packages/react-native/src/components/maps/DatePickers.tsx
  packages/react-native/src/hooks/useGallery.ts
  packages/react-native/src/pages/Maps/PostRecord.tsx
  packages/react-native/src/pages/Maps/Records.tsx
  packages/react-native/src/types/navigation.ts
  yarn.lock
Labels: feat

#24 feat: record post 리팩터링
  packages/design-system/src/TextField.tsx
  packages/react-native/src/apis/mutations/usePostRecordMutation.ts
  packages/react-native/src/apis/mutations/useRecordMutation.ts
  packages/react-native/src/assets/Calendar.tsx
  packages/react-native/src/components/maps/RecordFormDatePickers.tsx
  packages/react-native/src/components/maps/RecordFormDescription.tsx
  packages/react-native/src/components/maps/RecordFormTitle.tsx
  packages/react-native/src/components/maps/RecordPostForm.tsx
  packages/react-native/src/hooks/useRecordFormState.tsx
  packages/react-native/src/pages/Maps/PostRecord.tsx
Labels: refactor

#25 feat: 관광지 정보 SPOT 탭 슬라이더 추가
  packages/react-native/src/assets/CheckIcon.tsx
  packages/react-native/src/assets/CheckSelectedIcon.tsx
  packages/react-native/src/assets/CogWheelIcon.tsx
  packages/react-native/src/components/CardSlider.tsx
  packages/react-native/src/components/common/CardSlider.tsx
  packages/react-native/src/components/common/CheckBox.tsx
  packages/react-native/src/components/common/Header.tsx
  packages/react-native/src/components/detail/AroundCard.tsx
  packages/react-native/src/constants/DEFAULT_COLOR.ts
  packages/react-native/src/layouts/BackGroundGradient.tsx
  packages/react-native/src/pages/Detail.tsx
  packages/react-native/src/pages/Detail/DetailInfo.tsx
  packages/react-native/src/pages/Detail/DetailSpot.tsx
  packages/react-native/src/pages/Home.tsx
  packages/react-native/src/pages/MyPage.tsx
  packages/react-native/src/pages/Search.tsx
  packages/react-native/src/pages/Setting.tsx
  packages/react-native/src/routes/DetailTabNavigator.tsx
  packages/react-native/src/routes/SettingStackNavigator.tsx
  packages/react-native/src/routes/StackNavigator.tsx
  packages/react-native/src/types/navigation.ts
Labels: feat

#26 feat: Record 수정 기능 추가
  packages/react-native/src/apis/queries/records/useRecordDetailQuery.ts
  packages/react-native/src/components/maps/RecordFormImages.tsx
  packages/react-native/src/components/maps/RecordModifyForm.tsx
  packages/react-native/src/components/maps/RecordPostForm.tsx
  packages/react-native/src/hooks/useRecordFormState.tsx
  packages/react-native/src/pages/Maps/ModifyRecord.tsx
  packages/react-native/src/pages/Maps/RecordDetail.tsx
  packages/react-native/src/pages/Maps/Records.tsx
  packages/react-native/src/types/navigation.ts
Labels: feat

#27 feat: 지도 대표이미지 기능 추가
  packages/react-native/src/pages/Maps/Maps.tsx
Labels: feat

#29 feat: Quiz selection 화면 추가
  packages/react-native/src/apis/queries/quiz/useQuizQuery.ts
  packages/react-native/src/apis/queries/quiz/useQuizzesQuery.ts
  packages/react-native/src/components/gamification/QuizCard.tsx
  packages/react-native/src/components/gamification/QuizLoading.tsx
  packages/react-native/src/components/gamification/QuizSelection.tsx
  packages/react-native/src/components/gamification/QuizSlider.tsx
  packages/react-native/src/pages/Gamification/Gamification.tsx
  packages/react-native/src/pages/Gamification/Quiz.tsx
  packages/react-native/src/routes/GamificationStackNavigator.tsx
  packages/react-native/src/types/navigation.ts
Labels: feat

#30 feat: 지도 저장 기능 추가
  packages/react-native/src/assets/MapDownloadIcon.tsx
  packages/react-native/src/assets/MapSaveButtonIcon.tsx
  packages/react-native/src/hooks/useBottomSheet.tsx
  packages/react-native/src/hooks/useGallery.ts
  packages/react-native/src/pages/Gamification/Quiz.tsx
  packages/react-native/src/pages/Maps/Maps.tsx
Labels: feat

#31 feat: record form에 지역 선택 기능 추가
  packages/react-native/package.json
  packages/react-native/src/apis/mutations/useRecordMutation.ts
  packages/react-native/src/apis/mutations/useRecordRepresentativeMutation.ts
  packages/react-native/src/apis/queries/records/useRecordRepresentativeQuery.ts
  packages/react-native/src/components/maps/RecordFormCitySelect.tsx
  packages/react-native/src/components/maps/RecordModifyForm.tsx
  packages/react-native/src/components/maps/RecordPostForm.tsx
  packages/react-native/src/constants/CITY.ts
  packages/react-native/src/hooks/useRecordFormState.tsx
  packages/react-native/src/pages/Maps/Maps.tsx
  packages/react-native/src/utils/storage.ts
  yarn.lock
Labels: feat

#32 feat: mypage mock api연결
  packages/react-native/src/apis/mutations/useRecordRepresentativeMutation.ts
  packages/react-native/src/apis/queries/quiz/useQuizzesQuery.ts
  packages/react-native/src/apis/queries/useDetailQuery.ts
  packages/react-native/src/apis/queries/useNicknameQuery.ts
  packages/react-native/src/pages/Detail/DetailSpot.tsx
  packages/react-native/src/pages/Gamification/Gamification.tsx
  packages/react-native/src/pages/Gamification/Quiz.tsx
  packages/react-native/src/pages/Home.tsx
  packages/react-native/src/pages/MyPage.tsx
  packages/react-native/src/pages/MyPage/MySpot.tsx
  packages/react-native/src/pages/Signup/NicknameProfile.tsx
  packages/react-native/src/pages/Signup/Profile.tsx
  packages/react-native/src/utils/storage.ts
Labels: bug, feat

#33 feat: 활동배지 탭 추가
  packages/react-native/src/assets/EarthIcon.tsx
  packages/react-native/src/assets/RouteIcon.tsx
  packages/react-native/src/assets/badges/Busan.png
  packages/react-native/src/assets/badges/Chungbuk.png
  packages/react-native/src/assets/badges/Daegu.png
  packages/react-native/src/assets/badges/Daejeon.png
  packages/react-native/src/assets/badges/Gangwon.png
  packages/react-native/src/assets/badges/Gwangju.png
  packages/react-native/src/assets/badges/Gyeongbuk.png
  packages/react-native/src/assets/badges/Gyeonggi.png
  packages/react-native/src/assets/badges/Incheon.png
  packages/react-native/src/assets/badges/Jeju.png
  packages/react-native/src/assets/badges/Jeonbuk.png
  packages/react-native/src/assets/badges/Sejong.png
  packages/react-native/src/assets/badges/Seoul.png
  packages/react-native/src/assets/badges/Ulsan.png
  packages/react-native/src/components/common/Badge.tsx
  packages/react-native/src/components/mypage/BadgeListBottomSheet.tsx
  packages/react-native/src/components/mypage/BadgeListItem.tsx
  packages/react-native/src/components/mypage/Rank.tsx
  packages/react-native/src/pages/MyPage.tsx
  packages/react-native/src/pages/MyPage/MyBadge.tsx
  packages/react-native/src/pages/MyPage/MySpot.tsx
  packages/react-native/src/routes/BottomTabNavigator.tsx
  packages/react-native/src/routes/MyPageTabNavigator.tsx
Labels: feat

#34 feat: 랜딩 페이지 추가
  packages/react-native/src/components/landing/MockUp.tsx
  packages/react-native/src/pages/Home.tsx
  packages/react-native/src/pages/Landing.tsx
  packages/react-native/src/pages/Landing/Landing1.tsx
  packages/react-native/src/pages/Landing/Landing2.tsx
  packages/react-native/src/pages/Landing/Landing3.tsx
  packages/react-native/src/pages/Landing/Landing4.tsx
  packages/react-native/src/routes/StackNavigator.tsx
  packages/react-native/src/types/navigation.ts
Labels: feat

#35 feat: 카카오 지도 추가
  .gitignore
  packages/react-native/android/app/src/main/AndroidManifest.xml
  packages/react-native/babel.config.js
  packages/react-native/env.d.ts
  packages/react-native/ios/Podfile.lock
  packages/react-native/ios/SPOTClient.xcodeproj/project.pbxproj
  packages/react-native/ios/SPOTClient/Info.plist
  packages/react-native/package.json
  packages/react-native/src/pages/Detail/DetailInfo.tsx
  packages/react-native/src/pages/Detail/DetailMap.tsx
  yarn.lock
Labels: feat

#36 feat: Quiz 문제풀이 로직/Quiz 없는 경우 처리/로딩창 UI변경
  packages/react-native/src/apis/mutations/useQuizSubmitMutation.ts
  packages/react-native/src/components/gamification/NoQuiz.tsx
  packages/react-native/src/components/gamification/QuizCard.tsx
  packages/react-native/src/components/gamification/QuizLoading.tsx
  packages/react-native/src/components/gamification/QuizResultModal.tsx
  packages/react-native/src/constants/CITY.ts
  packages/react-native/src/pages/Gamification/Gamification.tsx
  packages/react-native/src/pages/Gamification/Quiz.tsx
Labels: feat

#37 refactor: 공통 컴포넌트 디자인 시스템으로 분리
  packages/design-system/index.ts
  packages/design-system/src/CheckBox.tsx
  packages/design-system/src/FloatingPlusButton.tsx
  packages/design-system/src/assets/BackIcon.tsx
  packages/design-system/src/assets/Calendar.tsx
  packages/design-system/src/assets/CancelIcon.tsx
  packages/design-system/src/assets/ChangeIcon.tsx
  packages/design-system/src/assets/CheckIcon.tsx
  packages/design-system/src/assets/CheckSelectedIcon.tsx
  packages/design-system/src/assets/CogWheelIcon.tsx
  packages/design-system/src/assets/DetailIcon.tsx
  packages/design-system/src/assets/DotMenuIcon.tsx
  packages/design-system/src/assets/DownloadIcon.tsx
  packages/design-system/src/assets/EarthIcon.tsx
  packages/design-system/src/assets/EditIcon.tsx
  packages/design-system/src/assets/HeartIcon.tsx
  packages/design-system/src/assets/HomeIcon.tsx
  packages/design-system/src/assets/MapDownloadIcon.tsx
  packages/design-system/src/assets/MapIcon.tsx
  packages/design-system/src/assets/MapSaveButtonIcon.tsx
  packages/design-system/src/assets/MyPageIcon.tsx
  packages/design-system/src/assets/PlusButtonIcon.tsx
  packages/design-system/src/assets/PlusIcon.tsx
  packages/design-system/src/assets/RouteIcon.tsx
  packages/design-system/src/assets/SPOTLogo.tsx
  packages/design-system/src/assets/Search.tsx
  packages/design-system/src/assets/SelectProfile.tsx
  packages/design-system/src/assets/SortIcon.tsx
  packages/design-system/src/assets/badges/Busan.png
  packages/design-system/src/assets/badges/Chungbuk.png
  packages/design-system/src/assets/badges/Daegu.png
  packages/design-system/src/assets/badges/Daejeon.png
  packages/design-system/src/assets/badges/Gangwon.png
  packages/design-system/src/assets/badges/Gwangju.png
  packages/design-system/src/assets/badges/Gyeongbuk.png
  packages/design-system/src/assets/badges/Gyeonggi.png
  packages/design-system/src/assets/badges/Incheon.png
  packages/design-system/src/assets/badges/Jeju.png
  packages/design-system/src/assets/badges/Jeonbuk.png
  packages/design-system/src/assets/badges/Sejong.png
  packages/design-system/src/assets/badges/Seoul.png
  packages/design-system/src/assets/badges/Ulsan.png
  packages/design-system/src/assets/map.png
  packages/design-system/src/assets/mapData.ts
  packages/design-system/stories/Checkbox.stories.tsx
  packages/design-system/stories/FloatingPlusButton.stories.tsx
  packages/react-native/src/components/detail/AroundCard.tsx
  packages/react-native/src/components/gamification/QuizSelection.tsx
  packages/react-native/src/pages/Maps/Records.tsx
Labels: refactor

#39 feat: my spot bottom sheet 추가
  packages/react-native/src/App.tsx
  packages/react-native/src/apis/queries/spot/useSpotDetailQuery.ts
  packages/react-native/src/components/mypage/BadgeListBottomSheet.tsx
  packages/react-native/src/components/mypage/MySpotBlock.tsx
  packages/react-native/src/components/mypage/MySpotDetailBottomSheet.tsx
  packages/react-native/src/hooks/useBottomSheet.tsx
  packages/react-native/src/pages/Detail/DetailMap.tsx
  packages/react-native/src/pages/Maps/Maps.tsx
  packages/react-native/src/pages/Maps/Records.tsx
  packages/react-native/src/pages/MyPage/MySpot.tsx
  packages/react-native/src/pages/TripPlanner/TripPlanner.tsx
Labels: feat

#40 feat: detail 뷰 spot 영역에 대한 bottom sheet기능 추가
  packages/design-system/src/assets/PlusButtonIcon.tsx
  packages/react-native/src/apis/queries/detail/useAroundSpotQuery.ts
  packages/react-native/src/components/common/BottomSheet.tsx
  packages/react-native/src/components/detail/AroundCard.tsx
  packages/react-native/src/components/mypage/BadgeListBottomSheet.tsx
  packages/react-native/src/components/mypage/MySpotDetailBottomSheet.tsx
  packages/react-native/src/hooks/useArrayToggle.ts
  packages/react-native/src/hooks/useBottomSheet.tsx
  packages/react-native/src/hooks/useToggle.ts
  packages/react-native/src/pages/Detail/DetailSpot.tsx
  packages/react-native/src/pages/Maps/Maps.tsx
  packages/react-native/src/pages/Maps/Records.tsx
  packages/react-native/src/pages/MyPage/MyBadge.tsx
  packages/react-native/src/pages/TripPlanner/TripPlanner.tsx
  packages/react-native/src/routes/DetailTabNavigator.tsx
Labels: feat

#41 feat: 여행 일정 추가 Form 추가
  packages/design-system/src/TextField.tsx
  packages/react-native/src/assets/PlusIcon.tsx
  packages/react-native/src/components/common/CitySelect.tsx
  packages/react-native/src/components/common/DateSelect.tsx
  packages/react-native/src/components/common/ImageSelect.tsx
  packages/react-native/src/components/maps/RecordFormCitySelect.tsx
  packages/react-native/src/components/maps/RecordFormDatePickers.tsx
  packages/react-native/src/components/maps/RecordFormImages.tsx
  packages/react-native/src/components/maps/RecordPostForm.tsx
  packages/react-native/src/components/tripPlan/RegionSelect.tsx
  packages/react-native/src/components/tripPlan/TripPlanCard.tsx
  packages/react-native/src/components/tripPlan/TripPlanPostForm.tsx
  packages/react-native/src/hooks/useRecordFormState.tsx
  packages/react-native/src/hooks/useTripPlanFormState.tsx
  packages/react-native/src/pages/TripPlanner/TripPlanner.tsx
  packages/react-native/src/pages/TripPlanner/TripPlannerPost.tsx
  packages/react-native/src/routes/TripPlannerStackNavigator.tsx
  packages/react-native/src/types/navigation.ts
Labels: feat

#42 feat: 기록이 없는 경우 UI추가
  packages/react-native/src/apis/queries/records/useRecordsQuery.ts
  packages/react-native/src/components/maps/RecordCard.tsx
  packages/react-native/src/components/maps/RecordCardList.tsx
  packages/react-native/src/hooks/useToggle.ts
  packages/react-native/src/pages/Maps/Records.tsx
Labels: feat

#43 feat: Empty plan화면 추가 및 컴포넌트 분리
  packages/react-native/src/apis/queries/tripPlan/useTripPlansQuery.ts
  packages/react-native/src/components/tripPlan/EmptyPlan.tsx
  packages/react-native/src/components/tripPlan/TripPlannerBottomSheet.tsx
  packages/react-native/src/pages/TripPlanner/TripPlanner.tsx
Labels: feat, refactor

#44 feat: 여행 일정 디테일 뷰 추가
  packages/react-native/src/apis/queries/detail/useAroundSpotQuery.ts
  packages/react-native/src/apis/queries/tripPlan/useTripPlanDetailQuery.ts
  packages/react-native/src/components/HOC/withSuspense.tsx
  packages/react-native/src/components/common/CardSlider.tsx
  packages/react-native/src/components/common/Loading.tsx
  packages/react-native/src/components/common/SpotDetailBottomSheet.tsx
  packages/react-native/src/components/detail/AroundCard.tsx
  packages/react-native/src/components/maps/RecordCard.tsx
  packages/react-native/src/components/tripPlan/TripPlannerBottomSheet.tsx
  packages/react-native/src/pages/Detail/DetailSpot.tsx
  packages/react-native/src/pages/MyPage/MySpot.tsx
  packages/react-native/src/pages/TripPlanner/TripPlanner.tsx
  packages/react-native/src/pages/TripPlanner/TripPlannerDetail.tsx
  packages/react-native/src/routes/TripPlannerStackNavigator.tsx
  packages/react-native/src/types/navigation.ts
  packages/react-native/src/utils/getDisplayRegionName.ts
Labels: feat

#45 feat: api 요청을 위한 token 관리 로직 추가
  packages/design-system/src/TextField.tsx
  packages/react-native/env.d.ts
  packages/react-native/src/apis/useAuthAxios.ts
  packages/react-native/src/hooks/useToken.ts
Labels: feat

#46 feat: nickname api 연동/공통 submit loading추가
  packages/react-native/src/App.tsx
  packages/react-native/src/apis/mutations/useNicknameColorMutation.ts
  packages/react-native/src/apis/mutations/useNicknameMutation.ts
  packages/react-native/src/apis/queries/useNicknameQuery.ts
  packages/react-native/src/apis/useAuthAxios.ts
  packages/react-native/src/assets/LoadingIcon.tsx
  packages/react-native/src/components/common/MutationLoadingModal.tsx
  packages/react-native/src/hooks/useProfileImage.tsx
  packages/react-native/src/pages/Home.tsx
  packages/react-native/src/pages/MyPage.tsx
  packages/react-native/src/pages/MyPage/EditProfile.tsx
  packages/react-native/src/pages/MyPage/EditProfileWithNickname.tsx
  packages/react-native/src/pages/Signup/Nickname.tsx
  packages/react-native/src/pages/Signup/NicknameProfile.tsx
Labels: feat

#47 feat: 여행 계획에 spot을 추가하는 UI구성
  packages/react-native/src/components/detail/AroundCard.tsx
  packages/react-native/src/components/tripPlan/TripPlanCard.tsx
  packages/react-native/src/pages/Detail/DetailSpot.tsx
  packages/react-native/src/pages/HomeSpotAdd.tsx
  packages/react-native/src/routes/HomeStackNavigator.tsx
  packages/react-native/src/types/navigation.ts
Labels: feat

#48 feat: 달력 추가
  package.json
  packages/react-native/ios/SPOTClient.xcodeproj/project.pbxproj
  packages/react-native/package.json
  packages/react-native/src/components/common/DateSelect.tsx
  packages/react-native/src/components/tripPlan/TripPlanPostForm.tsx
  packages/react-native/src/constants/CALENDAR_THEME.ts
  packages/react-native/src/hooks/useCalendar.ts
  yarn.lock
Labels: feat

#49 feat: 일정 수정 페이지 UI 추가
  packages/react-native/src/apis/queries/tripPlan/useTripPlanEditDetailQuery.ts
  packages/react-native/src/components/editPlan/EditPlanTitle.tsx
  packages/react-native/src/components/editPlan/ScheduleBlock.tsx
  packages/react-native/src/components/tripPlan/TripPlannerBottomSheet.tsx
  packages/react-native/src/hooks/useCalendar.ts
  packages/react-native/src/pages/TripPlanner/EditTripPlan.tsx
  packages/react-native/src/routes/TripPlannerStackNavigator.tsx
  packages/react-native/src/types/navigation.ts
  packages/react-native/src/utils/date.ts
Labels: feat

#50 feat: 프로필 사진 추가/수정 api연동
  packages/react-native/src/apis/mutations/useNicknameMutation.ts
  packages/react-native/src/apis/mutations/useProfileImageMutation.ts
  packages/react-native/src/apis/queries/useProfileQuery.ts
  packages/react-native/src/hooks/useProfileImage.tsx
  packages/react-native/src/pages/Home.tsx
  packages/react-native/src/pages/MyPage.tsx
  packages/react-native/src/pages/MyPage/EditProfile.tsx
  packages/react-native/src/pages/Signup/Profile.tsx
  packages/react-native/src/utils/storage.ts
Labels: feat

#51 feat: detail 페이지 좋아요, 담기 버튼 추가
  packages/react-native/src/pages/Detail.tsx
Labels: feat

#53 hotfix: 안드로이드 달력 출력 문제 해결
  packages/react-native/src/components/common/DateSelect.tsx
  packages/react-native/src/components/tripPlan/TripPlanPostForm.tsx
  packages/react-native/src/constants/CALENDAR_THEME.ts
Labels: bug

#54 feat: 카카오 로그인 기능 추가
  packages/react-native/android/app/build.gradle
  packages/react-native/android/app/src/main/AndroidManifest.xml
  packages/react-native/android/app/src/main/res/values/strings.xml
  packages/react-native/package.json
  packages/react-native/src/apis/mutations/useLoginMutation.ts
  packages/react-native/src/apis/queries/useProfileQuery.ts
  packages/react-native/src/hooks/useToken.ts
  packages/react-native/src/pages/Login/Login.tsx
  packages/react-native/src/pages/Splash.tsx
  packages/react-native/src/routes/StackNavigator.tsx
  packages/react-native/src/types/navigation.ts
  packages/react-native/src/types/response.ts
  packages/react-native/src/types/storage.ts
  packages/react-native/src/utils/storage.ts
  yarn.lock
Labels: feat

#55 feat: quiz api 연동
  packages/react-native/src/apis/mutations/useQuizSubmitMutation.ts
  packages/react-native/src/apis/queries/quiz/useQuizQuery.ts
  packages/react-native/src/apis/queries/quiz/useQuizzesQuery.ts
  packages/react-native/src/apis/queries/useProfileQuery.ts
  packages/react-native/src/components/gamification/QuizCard.tsx
  packages/react-native/src/components/gamification/QuizSlider.tsx
  packages/react-native/src/pages/Gamification/Quiz.tsx
  packages/react-native/src/pages/Home.tsx
  packages/react-native/src/types/navigation.ts
Labels: feat

#56 feat: 지도 대표이미지 지정 api 연동
  packages/react-native/src/apis/mutations/useProfileImageMutation.ts
  packages/react-native/src/apis/mutations/useRecordRepresentativeMutation.ts
  packages/react-native/src/apis/queries/records/useRecordRepresentativeQuery.ts
  packages/react-native/src/hooks/useGallery.ts
  packages/react-native/src/hooks/useProfileImage.tsx
  packages/react-native/src/pages/Maps/Maps.tsx
  packages/react-native/src/pages/MyPage/EditProfile.tsx
  packages/react-native/src/pages/Signup/Profile.tsx
  packages/react-native/src/utils/CustomForm.ts
Labels: feat

#57 hotfix: signup flow
  packages/react-native/src/apis/mutations/useLoginMutation.ts
  packages/react-native/src/apis/useAuthAxios.ts
Labels: bug

#52 feat: record api 연동
  packages/react-native/src/apis/mutations/useNicknameColorMutation.ts
  packages/react-native/src/apis/mutations/useNicknameMutation.ts
  packages/react-native/src/apis/mutations/useProfileImageMutation.ts
  packages/react-native/src/apis/mutations/useRecordMutation.ts
  packages/react-native/src/apis/mutations/useRecordRepresentativeMutation.ts
  packages/react-native/src/apis/queries/records/useRecordDetailQuery.ts
  packages/react-native/src/apis/queries/records/useRecordsQuery.ts
  packages/react-native/src/apis/queries/useProfileQuery.ts
  packages/react-native/src/components/common/BottomSheet.tsx
  packages/react-native/src/components/maps/RecordCard.tsx
  packages/react-native/src/components/maps/RecordCardList.tsx
  packages/react-native/src/components/maps/RecordFormDatePickers.tsx
  packages/react-native/src/components/maps/RecordModifyForm.tsx
  packages/react-native/src/components/maps/RecordPostForm.tsx
  packages/react-native/src/constants/QUERY_KEYS.ts
  packages/react-native/src/hooks/useRecordFormState.tsx
  packages/react-native/src/pages/Maps/RecordDetail.tsx
  packages/react-native/src/pages/Maps/Records.tsx
Labels: feat

#61 refactor: record post api
  packages/react-native/src/apis/mutations/useRecordMutation.ts
  packages/react-native/src/components/maps/RecordModifyForm.tsx
  packages/react-native/src/components/maps/RecordPostForm.tsx
Labels: bug, refactor

#63 fix: qa 적용
  packages/react-native/src/apis/mutations/useAddSchedule.ts
  packages/react-native/src/apis/mutations/useAddTripPlan.ts
  packages/react-native/src/apis/mutations/useDeleteTripPlan.ts
  packages/react-native/src/apis/queries/tripPlan/useTripPlanDetailQuery.ts
  packages/react-native/src/apis/queries/tripPlan/useTripPlansQuery.ts
  packages/react-native/src/components/common/Card.tsx
  packages/react-native/src/components/common/Header.tsx
  packages/react-native/src/components/tripPlan/TripPlanCard.tsx
  packages/react-native/src/components/tripPlan/TripPlanPostForm.tsx
  packages/react-native/src/components/tripPlan/TripPlannerBottomSheet.tsx
  packages/react-native/src/hooks/useTripPlanFormState.tsx
  packages/react-native/src/pages/Home.tsx
  packages/react-native/src/pages/Landing.tsx
  packages/react-native/src/pages/MyPage/EditProfile.tsx
  packages/react-native/src/pages/MyPage/MySpot.tsx
  packages/react-native/src/pages/Search.tsx
  packages/react-native/src/pages/TripPlanner/TripPlanner.tsx
  packages/react-native/src/pages/TripPlanner/TripPlannerDetail.tsx
  packages/react-native/src/routes/MyPageTabNavigator.tsx
  packages/react-native/src/types/navigation.ts
  packages/react-native/src/types/spot.ts
Labels: fix

#64 feat: TOS(Terms of policy) 화면 추가
  packages/design-system/src/CheckBox.tsx
  packages/react-native/src/apis/mutations/useLoginMutation.ts
  packages/react-native/src/components/toc/AgreeElement.tsx
  packages/react-native/src/components/toc/TOSBottomSheet.tsx
  packages/react-native/src/pages/Landing.tsx
  packages/react-native/src/pages/Splash.tsx
  packages/react-native/src/pages/TOS.tsx
  packages/react-native/src/routes/StackNavigator.tsx
  packages/react-native/src/types/navigation.ts
Labels: feat

#65 feat: spot api 연동
  packages/react-native/src/apis/mutations/useSpotLikeMutation.ts
  packages/react-native/src/apis/queries/detail/useAroundSpotQuery.ts
  packages/react-native/src/apis/queries/detail/useDetailQuery.ts
  packages/react-native/src/apis/queries/spot/useSpotDetailQuery.ts
  packages/react-native/src/apis/queries/tripPlan/useTripPlanDetailQuery.ts
  packages/react-native/src/apis/queries/useDetailQuery.ts
  packages/react-native/src/apis/queries/useHomeSpotQuery.ts
  packages/react-native/src/components/common/Card.tsx
  packages/react-native/src/components/common/SpotDetailBottomSheet.tsx
  packages/react-native/src/components/detail/AroundCard.tsx
  packages/react-native/src/constants/QUERY_KEYS.ts
  packages/react-native/src/pages/Detail.tsx
  packages/react-native/src/pages/Detail/DetailInfo.tsx
  packages/react-native/src/pages/Detail/DetailMap.tsx
  packages/react-native/src/pages/Detail/DetailSpot.tsx
  packages/react-native/src/pages/Home.tsx
  packages/react-native/src/routes/DetailTabNavigator.tsx
  packages/react-native/src/types/navigation.ts
  packages/react-native/src/types/spot.ts
Labels: feat

#66 fix: Record post, 여행기록 post api연동
  packages/react-native/src/apis/mutations/useAddTripPlan.ts
  packages/react-native/src/apis/mutations/useRecordMutation.ts
  packages/react-native/src/components/maps/RecordPostForm.tsx
  packages/react-native/src/components/tripPlan/TripPlanPostForm.tsx
Labels: fix

#67 feat: api 연결 추가
  packages/react-native/src/apis/mutations/useAddSchedule.ts
  packages/react-native/src/apis/mutations/useDeleteSchedule.ts
  packages/react-native/src/apis/mutations/useDeleteTripPlan.ts
  packages/react-native/src/apis/mutations/useUpdateTripPlanImage.ts
  packages/react-native/src/apis/queries/tripPlan/useTripPlanDetailQuery.ts
  packages/react-native/src/apis/queries/tripPlan/useTripPlanEditDetailQuery.ts
  packages/react-native/src/components/common/ImageSelect.tsx
  packages/react-native/src/components/tripPlan/TripPlannerBottomSheet.tsx
  packages/react-native/src/pages/TripPlanner/AddSchedule.tsx
  packages/react-native/src/pages/TripPlanner/EditTripPlan.tsx
Labels: feat

#69 feat: image delete 기능 추가
  packages/react-native/src/assets/DeleteIcon.tsx
  packages/react-native/src/components/common/ImageSelect.tsx
  packages/react-native/src/components/maps/RecordFormImages.tsx
Labels: feat

#70 feat: trip plan api 통합
  packages/react-native/src/apis/queries/tripPlan/useTripPlanDetailQuery.ts
  packages/react-native/src/assets/plan.png
  packages/react-native/src/pages/TripPlanner/TripPlanner.tsx
  packages/react-native/src/pages/TripPlanner/TripPlannerDetail.tsx
  packages/react-native/src/types/navigation.ts
Labels: feat

#72 feat: 여행 계획 기간 변경 UI 및 api연동
  packages/react-native/src/apis/mutations/useSchedulePeriodMutation.ts
  packages/react-native/src/components/tripPlan/TripPlannerBottomSheet.tsx
  packages/react-native/src/components/tripPlan/TripPlannerBottomSheetCalendar.tsx
  packages/react-native/src/components/tripPlan/TripPlannerBottomSheetOptions.tsx
Labels: feat

#73 feat: search api연동
  packages/react-native/src/apis/queries/detail/useAroundSpotQuery.ts
  packages/react-native/src/apis/queries/detail/useDetailQuery.ts
  packages/react-native/src/apis/queries/useSearchQuery.ts
  packages/react-native/src/components/common/Card.tsx
  packages/react-native/src/constants/QUERY_KEYS.ts
  packages/react-native/src/pages/Detail.tsx
  packages/react-native/src/pages/Detail/DetailInfo.tsx
  packages/react-native/src/pages/Detail/DetailSpot.tsx
  packages/react-native/src/pages/Search.tsx
  packages/react-native/src/routes/DetailTabNavigator.tsx
  packages/react-native/src/types/navigation.ts
Labels: feat

#75 fix: qa 적용
  packages/react-native/src/assets/landing/landing1.png
  packages/react-native/src/assets/landing/landing2.png
  packages/react-native/src/assets/landing/landing3.png
  packages/react-native/src/assets/landing/landing4.png
  packages/react-native/src/assets/landing/landing5.png
  packages/react-native/src/assets/landing/landing6.png
  packages/react-native/src/assets/landing/landing7.png
  packages/react-native/src/assets/plan.png
  packages/react-native/src/pages/Home.tsx
  packages/react-native/src/pages/Landing/Landing1.tsx
  packages/react-native/src/pages/Landing/Landing2.tsx
  packages/react-native/src/pages/Landing/Landing3.tsx
  packages/react-native/src/pages/Landing/Landing4.tsx
  packages/react-native/src/pages/Landing/Landing5.tsx
  packages/react-native/src/pages/Landing/Landing6.tsx
  packages/react-native/src/pages/Landing/Landing7.tsx
  packages/react-native/src/pages/TOS.tsx
  packages/react-native/src/pages/TripPlanner/TripPlannerDetail.tsx
Labels: fix

#71 feat: record patch api연동
  packages/react-native/src/apis/mutations/useRecordMutation.ts
  packages/react-native/src/components/maps/RecordFormImages.tsx
  packages/react-native/src/components/maps/RecordModifyForm.tsx
  packages/react-native/src/components/maps/RecordPostForm.tsx
  packages/react-native/src/hooks/useRecordFormState.tsx
  packages/react-native/src/pages/Maps/ModifyRecord.tsx
Labels: feat

#76 hotfix: qa2 반영
  packages/react-native/package.json
  packages/react-native/src/apis/queries/detail/useAroundSpotQuery.ts
  packages/react-native/src/components/common/Card.tsx
  packages/react-native/src/components/common/SpotDetailBottomSheet.tsx
  packages/react-native/src/constants/EMAIL_CONTENTS.ts
  packages/react-native/src/hooks/useSortByStartDate.ts
  packages/react-native/src/pages/Detail.tsx
  packages/react-native/src/pages/Detail/DetailSpot.tsx
  packages/react-native/src/pages/Maps/Records.tsx
  packages/react-native/src/pages/MyPage.tsx
  packages/react-native/src/pages/Setting.tsx
  packages/react-native/src/pages/TripPlanner/TripPlanner.tsx
  yarn.lock
Labels: fix

#78 feat: 공통 에러 처리
  packages/react-native/package.json
  packages/react-native/src/App.tsx
  packages/react-native/src/components/HOC/withSpotErrorBoundary.tsx
  packages/react-native/src/components/common/Error.tsx
  packages/react-native/src/hooks/useGeolocation.ts
  packages/react-native/src/pages/Splash.tsx
  packages/react-native/src/routes/StackNavigator.tsx
  yarn.lock
Labels: feat

#79 fix: qa 수정
  packages/react-native/src/components/editPlan/ScheduleBlock.tsx
  packages/react-native/src/components/tripPlan/TripPlanCard.tsx
  packages/react-native/src/pages/HomeSpotAdd.tsx
  packages/react-native/src/pages/TripPlanner/AddSchedule.tsx
Labels: fix

#80 hotfix: qa3번 피드백 반영
  packages/react-native/src/apis/queries/quiz/useQuizzesQuery.ts
  packages/react-native/src/components/common/CardSlider.tsx
  packages/react-native/src/components/gamification/QuizCard.tsx
  packages/react-native/src/components/toc/TOSBottomSheet.tsx
  packages/react-native/src/components/tripPlan/RegionSelect.tsx
  packages/react-native/src/pages/Detail/DetailInfo.tsx
  packages/react-native/src/pages/Detail/DetailSpot.tsx
  packages/react-native/src/pages/Setting.tsx
  packages/react-native/src/pages/Splash.tsx
  packages/react-native/src/pages/TripPlanner/TripPlannerDetail.tsx
  packages/react-native/src/utils/jugeokJosa.ts
Labels: fix

#83 fix: 일정 추가시 현재 선택한 날짜에 추가하도록 변경
  packages/react-native/src/apis/mutations/useAddSchedule.ts
  packages/react-native/src/pages/TripPlanner/AddSchedule.tsx
  packages/react-native/src/pages/TripPlanner/EditTripPlan.tsx
  packages/react-native/src/types/navigation.ts
Labels: fix

#84 feat: myspot api 연동
  packages/react-native/src/apis/mutations/useSpotLikeMutation.ts
  packages/react-native/src/apis/queries/mypage/useMySpotsQuery.ts
  packages/react-native/src/components/mypage/MySpotBlock.tsx
  packages/react-native/src/constants/QUERY_KEYS.ts
  packages/react-native/src/pages/MyPage.tsx
  packages/react-native/src/pages/MyPage/MySpot.tsx
  packages/react-native/src/routes/MyPageStackNavigator.tsx
  packages/react-native/src/types/navigation.ts
Labels: feat

#85 feat: badge api 연동
  packages/react-native/package.json
  packages/react-native/src/App.tsx
  packages/react-native/src/apis/mutations/useRecordRepresentativeMutation.ts
  packages/react-native/src/apis/queries/mypage/useMyBadgeQuery.ts
  packages/react-native/src/constants/QUERY_KEYS.ts
  packages/react-native/src/hooks/useGallery.ts
  packages/react-native/src/pages/Maps/Maps.tsx
  packages/react-native/src/pages/MyPage/EditProfile.tsx
  packages/react-native/src/pages/MyPage/MyBadge.tsx
  packages/react-native/src/pages/MyPage/MySpot.tsx
  packages/react-native/src/routes/MyPageTabNavigator.tsx
  packages/react-native/src/utils/CustomForm.ts
  packages/react-native/src/utils/storage.ts
  yarn.lock
Labels: feat

#86 config: sentry로 오류발생시 보고하도록 처리
  packages/react-native/android/app/build.gradle
  packages/react-native/env.d.ts
  packages/react-native/ios/Podfile.lock
  packages/react-native/ios/SPOTClient.xcodeproj/project.pbxproj
  packages/react-native/metro.config.js
  packages/react-native/package.json
  packages/react-native/src/App.tsx
  packages/react-native/src/components/HOC/withSpotErrorBoundary.tsx
  yarn.lock
Labels: feat

#87 config: React Native Code Push 안드로이드 적용
  .gitignore
  package.json
  packages/react-native/android/app/build.gradle
  packages/react-native/android/app/src/main/java/com/spotclient/MainApplication.kt
  packages/react-native/android/app/src/main/res/values/strings.xml
  packages/react-native/android/settings.gradle
  packages/react-native/codePush.sh
  packages/react-native/package.json
  packages/react-native/src/App.tsx
  yarn.lock
Labels: feat

#88 hotfix: quiz
  packages/react-native/src/apis/mutations/useQuizSubmitMutation.ts
  packages/react-native/src/components/common/SpotDetailBottomSheet.tsx
  packages/react-native/src/components/gamification/QuizResultModal.tsx
  packages/react-native/src/pages/Gamification/Quiz.tsx
Labels: bug

#89 hotfix: qa4 적용
  packages/design-system/src/Font.tsx
  packages/react-native/codePush.sh
  packages/react-native/src/apis/mutations/useRecordRepresentativeMutation.ts
  packages/react-native/src/apis/mutations/useSpotLikeMutation.ts
  packages/react-native/src/apis/queries/mypage/useMySpotsQuery.ts
  packages/react-native/src/components/common/AnimationCircle.tsx
  packages/react-native/src/components/common/Card.tsx
  packages/react-native/src/components/common/MutationLoadingModal.tsx
  packages/react-native/src/components/common/SpotDetailBottomSheet.tsx
  packages/react-native/src/components/detail/AroundCard.tsx
  packages/react-native/src/components/gamification/QuizLoading.tsx
  packages/react-native/src/components/maps/RecordPostForm.tsx
  packages/react-native/src/components/mypage/MySpotBlock.tsx
  packages/react-native/src/pages/CameraPage.tsx
  packages/react-native/src/pages/Detail/DetailInfo.tsx
  packages/react-native/src/pages/Landing/Landing1.tsx
  packages/react-native/src/pages/Landing/Landing2.tsx
  packages/react-native/src/pages/Landing/Landing3.tsx
  packages/react-native/src/pages/Landing/Landing4.tsx
  packages/react-native/src/pages/Landing/Landing5.tsx
  packages/react-native/src/pages/Landing/Landing6.tsx
  packages/react-native/src/pages/Landing/Landing7.tsx
  packages/react-native/src/pages/MyPage/MySpot.tsx
  packages/react-native/src/pages/TripPlanner/AddSchedule.tsx
  packages/react-native/src/pages/TripPlanner/TripPlannerDetail.tsx
Labels: bug, fix

#90 fix: QA사항 수정
  packages/react-native/src/components/common/DateSelect.tsx
  packages/react-native/src/components/maps/RecordPostForm.tsx
  packages/react-native/src/components/tripPlan/TripPlannerBottomSheetCalendar.tsx
  packages/react-native/src/hooks/useCalendar.ts
  packages/react-native/src/hooks/useProfileImage.tsx
  packages/react-native/src/hooks/useRecordFormState.tsx
  packages/react-native/src/hooks/useTripPlanFormState.tsx
  packages/react-native/src/pages/MyPage/EditProfile.tsx
  packages/react-native/src/utils/date.ts
Labels: fix

#91 feat: detail ui 변경 적용/bottom sheet뒤로가기로 닫을 수 있도록 처리
  packages/design-system/src/FloatingPlusButton.tsx
  packages/react-native/src/apis/mutations/useLoginMutation.ts
  packages/react-native/src/apis/mutations/useSignup.ts
  packages/react-native/src/apis/queries/common/useProfileQuery.ts
  packages/react-native/src/apis/queries/home/useHomeSpotQuery.ts
  packages/react-native/src/apis/queries/home/useSearchQuery.ts
  packages/react-native/src/components/common/BottomSheet.tsx
  packages/react-native/src/components/common/CardSlider.tsx
  packages/react-native/src/components/common/SpotDetailBottomSheet.tsx
  packages/react-native/src/components/detail/AroundCard.tsx
  packages/react-native/src/hooks/useAOSPreventBack.ts
  packages/react-native/src/hooks/useArrayToggle.ts
  packages/react-native/src/hooks/useProfileImage.tsx
  packages/react-native/src/pages/Detail/DetailSpot.tsx
  packages/react-native/src/pages/Home.tsx
  packages/react-native/src/pages/MyPage.tsx
  packages/react-native/src/pages/Search.tsx
  packages/react-native/src/routes/DetailTabNavigator.tsx
Labels: feat

#92 fix: authAxios
  packages/react-native/src/apis/queries/records/useRecordsQuery.ts
  packages/react-native/src/apis/useAuthAxios.ts
  packages/react-native/src/pages/Maps/Maps.tsx
  packages/react-native/src/pages/MyPage/MyBadge.tsx
  packages/react-native/src/pages/Setting.tsx
Labels: bug

#93 feat: codepush loading화면 추가
  packages/react-native/package.json
  packages/react-native/src/App.tsx
  packages/react-native/src/apis/queries/mypage/useMyBadgeQuery.ts
  packages/react-native/src/components/common/AnimationCircle.tsx
  packages/react-native/src/components/common/DateSelect.tsx
  packages/react-native/src/components/common/UpdateLoading.tsx
  packages/react-native/src/components/maps/RecordCard.tsx
  packages/react-native/src/components/maps/RecordPostForm.tsx
  packages/react-native/src/components/tripPlan/TripPlannerBottomSheet.tsx
  packages/react-native/src/hooks/useCodePush.tsx
  packages/react-native/src/pages/Detail/DetailSpot.tsx
  yarn.lock
Labels: bug, feat

#94 feat: 드래그 드랍으로 상세 일정 순서 변경 기능 추가
  packages/design-system/src/FloatingPlusButton.tsx
  packages/react-native/package.json
  packages/react-native/src/apis/mutations/useAddSchedule.ts
  packages/react-native/src/apis/mutations/useChangeScheduleOrder.ts
  packages/react-native/src/apis/mutations/useDeleteSchedule.ts
  packages/react-native/src/apis/queries/tripPlan/useTripPlanEditDetailQuery.ts
  packages/react-native/src/assets/MenuIcon.tsx
  packages/react-native/src/components/HOC/withSpotErrorBoundary.tsx
  packages/react-native/src/components/editPlan/ScheduleBlock.tsx
  packages/react-native/src/constants/QUERY_KEYS.ts
  packages/react-native/src/pages/MyPage/EditProfileWithNickname.tsx
  packages/react-native/src/pages/Signup/NicknameProfile.tsx
  packages/react-native/src/pages/TripPlanner/EditTripPlan.tsx
  yarn.lock
Labels: feat, fix

#96 feat: 필터 체험하기 기능 추가
  packages/react-native/android/app/build.gradle
  packages/react-native/codePush.sh
  packages/react-native/src/apis/queries/detail/useDetailQuery.ts
  packages/react-native/src/apis/queries/mypage/useMySpotsQuery.ts
  packages/react-native/src/apis/queries/quiz/useQuizzesQuery.ts
  packages/react-native/src/assets/filters/dokkaebi1.png
  packages/react-native/src/assets/filters/dokkaebi2.png
  packages/react-native/src/assets/filters/dongbaekkkotPilMuryeop1.png
  packages/react-native/src/assets/filters/dongbaekkkotPilMuryeop2.png
  packages/react-native/src/assets/filters/itaewonClass.png
  packages/react-native/src/assets/filters/mrSunshine.png
  packages/react-native/src/assets/filters/saranguiBulsiChak1.png
  packages/react-native/src/assets/filters/saranguiBulsiChak2.png
  packages/react-native/src/assets/filters/seumuldaseotSeumulHana1.png
  packages/react-native/src/assets/filters/seumuldaseotSeumulHana2.png
  packages/react-native/src/components/camera/CheckPhoto.tsx
  packages/react-native/src/components/camera/FilterCarousel.tsx
  packages/react-native/src/components/camera/SpotCamera.tsx
  packages/react-native/src/components/common/Card.tsx
  packages/react-native/src/components/gamification/FilterExperienceModal.tsx
  packages/react-native/src/components/gamification/NoQuiz.tsx
  packages/react-native/src/components/gamification/QuizCard.tsx
  packages/react-native/src/components/gamification/QuizResultModal.tsx
  packages/react-native/src/components/mypage/MySpotBlock.tsx
  packages/react-native/src/constants/BADGE_ACQUISITION.ts
  packages/react-native/src/constants/FILTER_PATHS.ts
  packages/react-native/src/pages/CameraPage.tsx
  packages/react-native/src/pages/Setting.tsx
  packages/react-native/src/types/navigation.ts
Labels: feat
