Repository TRIP-SPOT/SPOT-Client, pull requests merged in 2024-10, with the labels that each got.

#99 hotfix: qa 10/01
  packages/react-native/src/App.tsx
  packages/react-native/src/apis/mutations/useAddSchedule.ts
  packages/react-native/src/apis/mutations/useAddTripPlan.ts
  packages/react-native/src/apis/mutations/useDeleteTripPlan.ts
  packages/react-native/src/apis/mutations/useQuizSubmitMutation.ts
  packages/react-native/src/apis/queries/detail/useDetailQuery.ts
  packages/react-native/src/apis/queries/spot/useSpotDetailQuery.ts
  packages/react-native/src/apis/useAuthAxios.ts
  packages/react-native/src/components/tripPlan/TripPlanPostForm.tsx
  packages/react-native/src/constants/CITY.ts
  packages/react-native/src/pages/TripPlanner/AddSchedule.tsx
  packages/react-native/src/utils/removeHTMLTag.ts
Labels: bug, feat

#100 feat: 담은 SPOT 삭제 API 연결
  packages/react-native/src/apis/mutations/useDeleteSelectedSpotMutation.ts
  packages/react-native/src/apis/mutations/useRecordMutation.ts
  packages/react-native/src/apis/queries/spot/useSpotDetailQuery.ts
  packages/react-native/src/components/detail/AroundCard.tsx
  packages/react-native/src/pages/TripPlanner/TripPlannerDetail.tsx
Labels: feat

#101 hotfix: 10/01 qa 2
  packages/react-native/src/apis/queries/mypage/useMyBadgeQuery.ts
  packages/react-native/src/apis/queries/spot/useSpotDetailQuery.ts
  packages/react-native/src/apis/useAuthAxios.ts
  packages/react-native/src/pages/TripPlanner/TripPlannerDetail.tsx
Labels: bug

#102 feat: 홈화면 콘텐츠 추가
  packages/react-native/.eslintrc.js
  packages/react-native/src/assets/home/dokaebi.png
  packages/react-native/src/assets/home/dongbaek.png
  packages/react-native/src/assets/home/homecapture.png
  packages/react-native/src/assets/home/mrsunshine.png
  packages/react-native/src/assets/home/popular-spot.png
  packages/react-native/src/assets/home/sarang.png
  packages/react-native/src/assets/home/set-jetting.png
  packages/react-native/src/assets/home/setjettingtrend.png
  packages/react-native/src/assets/home/travellogcapture.png
  packages/react-native/src/assets/home/tripcapture.png
  packages/react-native/src/assets/home/tv.png
  packages/react-native/src/components/home/ContentImage.tsx
  packages/react-native/src/components/home/ContentTitle.tsx
  packages/react-native/src/components/home/SetJettingContent.tsx
  packages/react-native/src/components/home/contents/PopularSpot.tsx
  packages/react-native/src/components/home/contents/SetJetting.tsx
  packages/react-native/src/constants/HOME_CONTENTS.ts
  packages/react-native/src/pages/Home/Content.tsx
  packages/react-native/src/pages/Home/Detail.tsx
  packages/react-native/src/pages/Home/Home.tsx
  packages/react-native/src/pages/Home/HomeSpotAdd.tsx
  packages/react-native/src/pages/Home/Search.tsx
  packages/react-native/src/routes/HomeStackNavigator.tsx
  packages/react-native/src/routes/MyPageStackNavigator.tsx
  packages/react-native/src/types/navigation.ts
Labels: feat

#104 hotfix: 1007 qa 적용
  packages/react-native/src/pages/Home/Detail.tsx
  packages/react-native/src/pages/Home/HomeSpotAdd.tsx
  packages/react-native/src/pages/Maps/Maps.tsx
  packages/react-native/src/routes/MyPageStackNavigator.tsx
  packages/react-native/src/types/navigation.ts
Labels: bug

#105 feat: 홈 화면 내 주변 SPOT 영역 추가
  packages/react-native/src/apis/queries/home/useHomeSpotQuery.ts
  packages/react-native/src/apis/queries/home/useNearbySoptQuery.ts
  packages/react-native/src/apis/queries/quiz/useQuizzesQuery.ts
  packages/react-native/src/components/common/Card.tsx
  packages/react-native/src/components/home/contents/PopularSpot.tsx
  packages/react-native/src/constants/MILLISECONDS.ts
  packages/react-native/src/constants/QUERY_KEYS.ts
  packages/react-native/src/hooks/useLocation.ts
  packages/react-native/src/pages/Gamification/Gamification.tsx
  packages/react-native/src/pages/Home/Home.tsx
Labels: feat, fix

#106 hotfix: qa1011
  packages/react-native/src/apis/queries/home/useNearbySoptQuery.ts
  packages/react-native/src/components/common/SearchBar.tsx
  packages/react-native/src/hooks/useGeolocation.ts
  packages/react-native/src/hooks/useLocation.ts
  packages/react-native/src/pages/Detail/DetailSpot.tsx
  packages/react-native/src/routes/DetailTabNavigator.tsx
Labels: bug, feat

#107 feat: 이미지 없을 경우 로고 표시
  packages/react-native/src/components/common/Card.tsx
  packages/react-native/src/components/detail/AroundCard.tsx
  packages/react-native/src/components/gamification/QuizCard.tsx
  packages/react-native/src/components/mypage/MySpotBlock.tsx
  packages/react-native/src/pages/Home/Home.tsx
Labels: feat, fix

#109 docs: README 구조, 기술스택 추가
  README.md
Labels: documentation
